export enum ErrorCodes {
  // Client-Side Errors (4xx)
  BAD_REQUEST_ERROR = "ERR_BAD_REQUEST",
  UNAUTHORIZED_ERROR = "ERR_UNAUTHORIZED",
  FORBIDDEN_ERROR = "ERR_FORBIDDEN",
  NOT_FOUND_ERROR = "ERR_NOT_FOUND",
  METHOD_NOT_ALLOWED_ERROR = "ERR_METHOD_NOT_ALLOWED",
  NOT_ACCEPTABLE_ERROR = "ERR_NOT_ACCEPTABLE",
  CONFLICT_ERROR = "ERR_CONFLICT",
  GONE_ERROR = "ERR_GONE",
  UNPROCESSABLE_ENTITY_ERROR = "ERR_UNPROCESSABLE_ENTITY",
  TOO_MANY_REQUESTS_ERROR = "ERR_TOO_MANY_REQUESTS",
  PRECONDITION_FAILED_ERROR = "ERR_PRECONDITION_FAILED",

  //   Server-Side Errors (5xx)
  INTERNAL_SERVER_ERROR = "ERR_INTERNAL_SERVER_ERROR",
  NOT_IMPLEMENTED_ERROR = "ERR_NOT_IMPLEMENTED",
  BAD_GATEWAY_ERROR = "ERR_BAD_GATEWAY",
  SERVICE_UNAVAILABLE_ERROR = "ERR_SERVICE_UNAVAILABLE",
  GATEWAY_TIMEOUT_ERROR = "ERR_GATEWAY_TIMEOUT",
  HTTP_VERSION_NOT_SUPPORTED_ERROR = "ERR_HTTP_VERSION_NOT_SUPPORTED",

  //   Validation Errors
  VALIDATION_ERROR = "ERR_VALIDATION_ERROR",
  FIELD_REQUIRED_ERROR = "ERR_FIELD_REQUIRED_ERROR",
  FIELD_LENGTH_ERROR = "ERR_FIELD_LENGTH_ERROR",
  FIELD_FORMAT_ERROR = "ERR_FIELD_FORMAT_ERROR",

  //   Authentication & Authorization Errors
  AUTHENTICATION_ERROR = "ERR_AUTHENTICATION",
  AUTHORIZATION_ERROR = "ERR_AUTHORIZATION",
  TOKEN_EXPIRED_ERROR = "ERR_TOKEN_EXPIRED",
  TOKEN_INVALID_ERROR = "ERR_TOKEN_INVALID",
  SESSION_TIMEOUT_ERROR = "ERR_SESSION_TIMEOUT",

  //   Database Errors
  DATABASE_CONNECTION_ERROR = "ERR_DATABASE_CONNECTION",
  RECORD_NOT_FOUND_ERROR = "ERR_RECORD_NOT_FOUND",
  DUPLICATE_KEY_ERROR = "ERR_DUPLICATE_KEY",
  QUERY_TIMEOUT_ERROR = "ERR_QUERY_TIMEOUT",
  DATABASE_VALIDATION_ERROR = "ERR_DATABASE_VALIDATION",

  //   File Errors
  FILE_UPLOAD_ERROR = "ERR_FILE_UPLOAD",
  FILE_NOT_FOUND_ERROR = "ERR_FILE_NOT_FOUND",
  FILE_PERMISSION_ERROR = "ERR_FILE_PERMISSION",
  FILE_TOO_LARGE_ERROR = "ERR_FILE_TOO_LARGE",

  //   External Service Errors
  EXTERNAL_SERVICE_ERROR = "ERR_EXTERNAL_SERVICE",
  SERVICE_TIMEOUT_ERROR = "ERR_SERVICE_TIMEOUT",

  //   Rate Limiting Errors
  RATE_LIMIT_EXCEEDED_ERROR = "ERR_RATE_LIMIT_EXCEEDED",

  //   Application-Specific Errors
  FEATURE_NOT_ENABLED_ERROR = "ERR_FEATURE_NOT_ENABLED",
  INVALID_STATE_ERROR = "ERR_INVALID_STATE",
  OPERATION_FAILED_ERROR = "ERR_OPERATION_FAILED",
  INVALID_INPUT_ERROR = "ERR_INVALID_INPUT",

  //   Unknown Error
  UNKNOWN_ERROR = "ERR_UNKNOWN",
}
